### PR TITLE
Smithgeek/msvc fix compiling issues

### PR DESCRIPTION
**Pull request by phs**
Eagerly rebasing just to get the dev cycle a bit faster.

### CODE REVIEW

**Comment by victorbotamedi** [comment]
I've been using this branch in VS2013 and the tutorial test fails in release only (Release with debug info works).
Basically it throws a CircularDependencyException between Router and sauce::Injector due to setInjector method. As a i said, occurs only in release.

**Comment by victorbotamedi** [comment]
By turning on the /INCREMENTAL link it works as expected

**Comment by phs** [comment]
Huh, thanks for the data point.  Is one linking model or the other considered more "canonical"?

Also, offhand I don't suppose you have experience using [dependency walker](http://dependencywalker.com/) & could point me at what I'm doing wrong in console mode (see latest commits)?

**Comment by phs** [comment]
Reminding myself to become clueful: https://dev.modern.ie/tools/vms/mac/

**Comment by phs** [comment]
Note to myself, the wrapper executable generated by libtool is what's causing problems.  Recall libtool hides the _real_ binary in `.libs`, and where you think you get the binary, instead a "wrapper script" is placed.  This does various shenanigans to preserve some needed environment.

On windows machines, it is not a script but an executable.  In a local vm I can conform that it even responds to `--lt-dump-script` and `--lt-debug`, which are the only things one can get it to do besides the delegation.

**Pull request merged**
